### ISSUE TITLE
Markdown Editor 'start' and 'final' files are the same

### ISSUE THREAD

**Issue by smithbm2316** [chris-on-code/20-react-apps#4]
Hey Chris, thanks for the course, been really enjoying the videos so far! Just wanted to let you know that the 'start' and 'final' folders for 'markdown-editor' have the same code in 'App.js'. Both of them are showing the final code for the markdown editor project. Not really a huge issue as the video was pretty straightforward, but I just wanted to give you a heads up! 😃

**Comment by chris-sev** [comment]
Thanks for letting me know. Fixed by fe144ab21e6f778eb7f0d20ae7e957899d4f0273
