### ISSUE TITLE
Some of the README.md links aren't right

### ISSUE THREAD

**Issue by thedavedavies** [chris-on-code/20-react-apps#5]
Hey Chris,

The Pomodoro **Preview** and **Demo** links in [this section](https://github.com/chris-on-code/20-react-apps#the-20-apps--preview--demo) aren't right. 

Also the **Infinite Image Gallery** demo link doesn't go anywhere.

Probably too minor for a pull request, but figured you'd wanna know 🙂

**Comment by chris-sev** [comment]
Hey. I've got the Pomodoro links fixed up by b1d9cc4c748bbc35f7c201c22b3516b3b9d65de7

The Image Gallery links look alright though.

```
1. [Infinite Image Gallery](https://github.com/chris-on-code/20-react-apps/tree/master/image-gallery) - [Preview](https://courses.chrisoncode.io/courses/make-20-react-apps/257611-infinite-image-gallery/748761-00-infinite-image-gallery-preview) - [Demo](https://e9ucz.csb.app/)
```

**Comment by thedavedavies** [comment]
Is your **Infinite Image Gallery** codesandbox example in private mode? I was in FF before, and just got a white screen. This is what I see in Chrome (latest) and FF (nightly) side-by-side.

<img width="1768" alt="Screenshot 2020-04-25 at 15 02 37" src="https://user-images.githubusercontent.com/2972436/80281840-ee405080-8705-11ea-8337-edc8eca179b3.png">

**Comment by chris-sev** [comment]
Good call! That was exactly it.

Should be good now: https://e9ucz.csb.app/

**Comment by thedavedavies** [comment]
Works perfect now, thanks 🙂 Loving the course, by the way. It's exactly the hooks resource I was looking for.

**Comment by chris-sev** [comment]
That's great to hear! And thanks for the help. Really appreciate it.
